### ISSUE TITLE
Driver modification

### ISSUE THREAD

**Issue by shomahi** [JetsonHacksNano/buildKernelAndModules#11]
Hi,

I need to add adv7280m support in the jetson nano drivers. How can I apply the modifications in dtb files and sources then using your scripts to make the kernel. I'd appreciate if you can let me know.

**Comment by JetsonHacksNano** [comment]
This is beyond what this repository supports. Please ask your question on the official NVIDIA Jetson Nano forum, where a large group of developers and NVIDIA engineers share their experience: https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76
