### ISSUE TITLE
[BUG] Wrong download URL for T210

### ISSUE THREAD

**Issue by enetkilifatih** [JetsonHacksNano/buildKernelAndModules#14]
**Describe the issue**
`getKernelSources.sh` script selects `t186` url for `t210` boards.

**Which version of Ubuntu on the Host machine**
Ubuntu version: 20.04.1

**What version of L4T/JetPack**
L4T/JetPack version:  L4T 32.6.1 / JetPack 4.6

**Which Jetson**
Jetson: Nano

**To Reproduce**
- Use Jetson Nano, Nano 2GB or TX1
- Clone `buildKernelAndModules` repository
- Run `./getKernelSources.sh`

**Expected behavior**
`getKernelSources.sh` script to select right download url is expected.

**Comment by JetsonHacksNano** [comment]
Fixed in v1.1
