### ISSUE TITLE
How complicated would it be to build kernel 5.10 for Jetson Nano?

### ISSUE THREAD

**Issue by bmilde** [JetsonHacksNano/buildKernelAndModules#18]
Nvidia released Jetpack 5 with Linux kernel 5.10 support, but its only for their high-end development platforms (AGX and Orin). Tegra 210 (Jetson Nano) is stuck on kernel 4.9 and jetpack 4.x.

How difficult and feasible would it be, to cook up a Jetson Nano compatible kernel 5 from Nvidia's public sources (https://developer.nvidia.com/embedded/jetson-linux)?

**Comment by JetsonHacksNano** [comment]
I do not know. You can look through this: https://forums.developer.nvidia.com/t/upgrading-kernel-to-5/112113
