### ISSUE TITLE
Jetson BSP Version:  L4T R32.2.0  not L4T R32.2

### ISSUE THREAD

**Issue by tmichals** [JetsonHacksNano/buildKernelAndModules#2]
**getKernelSources:**

lcs@nano:~/buildKernelAndModules$ ./getKernelSources.sh
Jetson Model: NVIDIA Jetson Nano Developer Kit
Getting L4T Version
 Jetson BSP Version:  L4T R32.2.0
Jetson_L4T=32.2.0

**Produces Error:**
This repository is for modifying the kernel for a L4T 32.2 system.
You are attempting to modify a L4T NVIDIA Jetson Nano Developer Kit system with L4T 32.2.0
The L4T releases must match!

What is the standard.  32.2 or 32.2.0 ?

**Comment by tmichals** [comment]
I modified getKernelSources.sh to  L4T R32.2.0 seemed to work fine.

**Comment by JetsonHacksNano** [comment]
Thank you for pointing this out. The new L4T 32.2.1 version has this fixed.
