### ISSUE TITLE
Activate SPI-CAN (MCP2515)

### ISSUE THREAD

**Issue by ADV-LUT** [JetsonHacksNano/buildKernelAndModules#3]
Hello,

I want to activate CAN on the Jetson board and this with the MCP251x. How should I activate this? How are the right steps?

Is it enough to update the MCP251x or do I also have to activate SPI and which SPI needs to be activated?

I found the CAN bus under Netweork Support, but I do not know what to do next.

Many thanks for the help.

**Comment by JetsonHacksNano** [comment]
I do not have anything to share on this subject. Please ask this question of the official NVIDIA Nano Developers forum where a large number of developers and NVIDIA Engineers share their experience.
