### ISSUE TITLE
Request Update to L4T 32.2.3

### ISSUE THREAD

**Issue by vusdo** [JetsonHacksNano/buildKernelAndModules#4]
Thank you always.

I am requesting a Github update for this updated L4T 23.2.3. I am waiting.

**Comment by majorpr13** [comment]
Executing the patchUbuntu.sh from the installRealsense repository leads to a mismatch on the L4T_TARGET. Updating this to the appropriate 32.2.3 version then has a mismatch within this directory. Is there a way to correct this?

**Comment by paddygoat** [comment]
Anything for L4T 32.2.3 ????
Thanks.

**Comment by paddygoat** [comment]
How can I be sure that the version from the SD card image download is compatible?
Or should I flash the Nano from a linux host using the SDK?

**Comment by nusseibeh** [comment]
I believe you can get this working by replacing the link in line 18 of "scripts/getKernelSources.sh" with the L4T version of your choosing. You can get the appropriate source link from the L4T archive: https://developer.nvidia.com/embedded/linux-tegra-archive

For 32.2.3 you'll want this link: https://developer.nvidia.com/embedded/r32-2-3_Release_v1.0/Sources/T210/public_sources.tbz2

You'll also need to update the "L4T_TARGET" variable in "getKernelSources.sh" to 32.2.3.
