### ISSUE TITLE
Kernel for L4T 32.4.2

### ISSUE THREAD

**Issue by iscsrl** [JetsonHacksNano/buildKernelAndModules#8]
"You are attempting to modify a L4T NVIDIA Jetson Nano Developer Kit system with L4T 32.4.2"
How can I proceed with the kernel and modules update?

**Comment by nusseibeh** [comment]
I believe you can get this working by replacing the link in line 18 of "scripts/getKernelSources.sh" with the L4T version of your choosing. You can get the appropriate source link from the L4T archive: https://developer.nvidia.com/embedded/linux-tegra-archive

For 32.4.2 you'll want this link: https://developer.nvidia.com/embedded/L4T/r32_Release_v4.2/Sources/T210/public_sources.tbz2

You'll also need to update the "L4T_TARGET" variable in "getKernelSources.sh" to 32.4.2.

**Comment by JetsonHacksNano** [comment]
Fixed in v1.1.
